# 日志
logging:
  level:
    root: warn
    com.hzhang: info
  file:
    name: log/blog-prod.log
# 端口号
server:
  port: 80

spring:
  #    数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
