# 日志
logging:
  level:
    root: warn
    com.hzhang: info
  file:
    name: log/blog-prod.log
# 端口号
server:
  port: 8080

spring:
  #    redis
  redis:
    host: xxx
    port: 6379
    password: xxx
  #    数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxx/blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: xxx
