# 日志
logging:
  level:
    root: warn
    com.hzhang: info
  file:
    name: log/blog-prod.log
# 端口号
server:
  port: 8080

spring:
  #    redis
  redis:
    host: redis
    port: 6379
    password: ***
#    rabbitmq
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 10
  #    数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: ***
